# Lab CLI Configuration
# Network configuration
network: "10.11.3.0/24"

apt-cache-ct: apt-cache 

# Template generation configuration
templates:
  - name: ubuntu-tmpl
    id: 3010
    ip: 10  # Last octet only
    hostname: "ubuntu-tmpl"
    type: ubuntu
    template: base
    resources:
      memory: 2048
      swap: 2048
      cores: 4
      rootfs_size: 20
    actions:
      - apt cache proxy configuration
      - AppArmor parser stub
      - apt sources fix
      - system upgrade
      - openssh-server installation
      - SSH service enablement
      - base tools installation
      - template cleanup
      - template archive creation
  - name: docker-tmpl
    id: 3008
    ip: 8  # Last octet only
    hostname: "docker-tmpl"
    type: ubuntu+docker
    template: ubuntu-tmpl
    resources:
      memory: 4096
      swap: 4096
      cores: 8
      rootfs_size: 40
    actions:
      - Docker installation
      - Docker service start
      - template cleanup
      - template archive creation


ct:
  - name: apt-cache
    id: 3020
    ip: 20  # Last octet only
    hostname: "apt-cache"
    type: apt-cache
    template: ubuntu-tmpl
    resources:
      memory: 2048
      swap: 2048
      cores: 4
      rootfs_size: 20
    actions:
      - cloud-init wait
      - AppArmor parser stub
      - disable automatic apt units
      - systemd sysctl override
      - apt-cacher-ng installation
      - apt-cacher-ng port configuration
      - apt-cacher-ng service enablement
  - name: pgsql
    id: 3018
    ip: 18  # Last octet only
    hostname: "pgsql"
    type: pgsql
    template: ubuntu-tmpl
    resources:
      memory: 2048
      swap: 2048
      cores: 2
      rootfs_size: 30
    params:
      version: "17"
      port: 5432
      data_dir: "/var/lib/postgresql/data"
    actions:
      - cloud-init wait
      - postgresql installation
      - postgresql service configuration
      - postgresql files configuration
      - postgresql password setup
  - name: haproxy
    id: 3017
    ip: 17  # Last octet only
    hostname: "haproxy"
    type: haproxy
    template: ubuntu-tmpl
    resources:
      memory: 1024
      swap: 1024
      cores: 2
      rootfs_size: 10
    params:
      http_port: 80
      https_port: 443
      stats_port: 8404
    actions:
      - cloud-init wait
      - haproxy installation
      - haproxy configuration
      - haproxy systemd override
      - haproxy service enablement
  - name: dns
    id: 3019
    ip: 19  # Last octet only
    hostname: "dns"
    type: dns
    template: docker-tmpl
    resources:
      memory: 2048
      swap: 2048
      cores: 4
      rootfs_size: 20
    params:
      dns_port: 53
      web_port: 80
      postgres_host: "10.11.3.18"
      postgres_port: 5432
      postgres_db: "dns_server"
      postgres_user: "postgres"
      postgres_password: "postgres"
    actions:
      - cloud-init wait
      - dotnet installation
      - disable systemd resolved
      - sins dns installation
      - sins dns service configuration
      - sins dns service enablement
  - name: swarm-manager
    id: 3005
    ip: 5  # Last octet only
    hostname: "swarm-manager"
    type: swarm-manager
    template: docker-tmpl
    resources:
      memory: 4096
      swap: 4096
      cores: 8
      rootfs_size: 40
    params:
      port: 2377
    actions:
      - cloud-init wait
      - lxc sysctl access configuration
      - docker service start
      - docker sysctl configuration
  - name: swarm-node-1
    id: 3006
    ip: 6  # Last octet only
    hostname: "swarm-node-1"
    type: swarm-node
    template: docker-tmpl
    resources:
      memory: 4096
      swap: 4096
      cores: 8
      rootfs_size: 40
    params:
      port: 2377
    actions:
      - cloud-init wait
      - docker service start
  - name: swarm-node-2
    id: 3007
    ip: 7  # Last octet only
    hostname: "swarm-node-2"
    type: swarm-node
    template: docker-tmpl
    resources:
      memory: 4096
      swap: 4096
      cores: 8
      rootfs_size: 40
    params:
      port: 2377
    actions:
      - cloud-init wait
      - docker service start

swarm:
  managers:
    - id: 3005
  workers:
    - id: 3006
    - id: 3007

# Script timeouts (in seconds)
timeouts:
  apt_cache: 900
  ubuntu_template: 1200
  docker_template: 1500
  swarm_deploy: 2400

# Proxmox/LXC constants
proxmox:
  host: "root@10.11.3.4"
  storage: "sdb"
  bridge: "vmbr0"
  template_dir: "/var/lib/vz/template/cache"
  gateway_octet: 253  # Last octet of gateway IP

# User configuration
users:
  - name: "jaal"
    password: "jaal123"
    sudo_group: "sudo"

# Network services
services:
  apt_cache:
    port: 3142
  docker_swarm:
    port: 2377
  portainer:
    port: 9443
    image: "portainer/portainer-ce:latest"
  postgresql:
    port: 5432
  haproxy:
    http_port: 80
    https_port: 443
    stats_port: 8404

# DNS servers
dns:
  servers:
    - "8.8.8.8"
    - "8.8.4.4"
    - "10.11.2.5"

# Docker configuration
docker:
  version: "28.4.0"
  repository: "noble"
  release: "stable"
  ubuntu_release: "24.04"

# Base templates and patterns
template_config:
  base:
    - "ubuntu-25.04-standard_25.04-1.1_amd64.tar.zst"
#    - "ubuntu-24.04-standard_24.04-1_amd64.tar.zst"
#    - "ubuntu-24.10-standard_24.10-1_amd64.tar.zst"
  patterns:
    ubuntu: "ubuntu-25.04-template_{date}_amd64.tar.zst"
    "ubuntu+docker": "docker-ubuntu25.04-template_{date}_amd64.tar.zst"
  preserve:
    - "ubuntu-24.10-standard_24.10-1_amd64.tar.zst"
    - "ubuntu-25.04-template_*.tar.zst"
    - "docker-ubuntu25.04-template_*.tar.zst"

# SSH configuration
ssh:
  connect_timeout: 10
  batch_mode: true

# Wait/retry configuration
waits:
  container_startup: 20
  container_ready_max_attempts: 30
  container_ready_sleep: 3
  network_config: 5
  service_start: 10
  swarm_init: 5
  portainer_start: 10
  glusterfs_setup: 30

# GlusterFS distributed storage configuration
glusterfs:
  volume_name: "swarm-storage"
  brick_path: "/gluster/brick"
  mount_point: "/mnt/gluster"
  replica_count: 2  # Replicate across 2 worker nodes

