# Lab CLI Configuration
# Network configuration
network: "10.11.3.0/24"

# apt-cacher-ng container configuration
apt_cache:
  id: 3020
  ip: 20  # Last octet only
  hostname: "apt-cacher-ng"

# Ubuntu template generation configuration
ubuntu_template:
  id: 3010
  ip: 10  # Last octet only
  hostname: "ubuntu-template"

# Docker template generation configuration
docker_template:
  id: 3008
  ip: 8  # Last octet only
  hostname: "docker-template"

# PostgreSQL container configuration
postgresql:
  id: 3018
  ip: 18  # Last octet only
  hostname: "postgresql"
  version: "17"
  port: 5432
  data_dir: "/var/lib/postgresql/data"

# HAProxy load balancer configuration
haproxy:
  id: 3017
  ip: 17  # Last octet only
  hostname: "haproxy"
  http_port: 80
  https_port: 443
  stats_port: 8404

# Docker Swarm deployment configuration
swarm:
  manager:
    id: 3005
    ip: 5  # Last octet only
    hostname: "docker-manager"
  workers:
    - id: 3006
      ip: 6  # Last octet only
      hostname: "docker-node-1"
    - id: 3007
      ip: 7  # Last octet only
      hostname: "docker-node-2"

# Script timeouts (in seconds)
timeouts:
  apt_cache: 900
  ubuntu_template: 1200
  docker_template: 1500
  swarm_deploy: 2400

# Proxmox/LXC constants
proxmox:
  host: "root@10.11.3.4"
  storage: "sdb"
  bridge: "vmbr0"
  template_dir: "/var/lib/vz/template/cache"
  gateway_octet: 253  # Last octet of gateway IP

# Container resource defaults
containers:
  apt_cache:
    memory: 2048
    swap: 2048
    cores: 4
    rootfs_size: 20
  ubuntu_template:
    memory: 2048
    swap: 2048
    cores: 4
    rootfs_size: 20
  docker_template:
    memory: 4096
    swap: 4096
    cores: 8
    rootfs_size: 40
  swarm_nodes:
    memory: 4096
    swap: 4096
    cores: 8
    rootfs_size: 40
  postgresql:
    memory: 2048
    swap: 2048
    cores: 2
    rootfs_size: 30
  haproxy:
    memory: 1024
    swap: 1024
    cores: 2
    rootfs_size: 10

# User configuration
users:
  default_user: "jaal"
  sudo_group: "sudo"

# Network services
services:
  apt_cache:
    port: 3142
  docker_swarm:
    port: 2377
  portainer:
    port: 9443
    image: "portainer/portainer-ce:latest"
  postgresql:
    port: 5432
  haproxy:
    http_port: 80
    https_port: 443
    stats_port: 8404

# DNS servers
dns:
  servers:
    - "8.8.8.8"
    - "8.8.4.4"
    - "10.11.2.5"

# Docker configuration
docker:
  version: "28.4.0"
  repository: "noble"
  release: "stable"
  ubuntu_release: "24.04"

# Base templates
templates:
  base:
    - "ubuntu-24.04-standard_24.04-1_amd64.tar.zst"
    - "ubuntu-24.10-standard_24.10-1_amd64.tar.zst"
  ubuntu_template_pattern: "ubuntu-25.04-template_{date}_amd64.tar.zst"
  docker_template_pattern: "docker-ubuntu25.04-template_{date}_amd64.tar.zst"
  preserve:
    - "ubuntu-24.10-standard_24.10-1_amd64.tar.zst"
    - "ubuntu-25.04-template_*.tar.zst"
    - "docker-ubuntu25.04-template_*.tar.zst"

# SSH configuration
ssh:
  connect_timeout: 10
  batch_mode: true

# Wait/retry configuration
waits:
  container_startup: 20
  container_ready_max_attempts: 30
  container_ready_sleep: 3
  network_config: 5
  service_start: 10
  swarm_init: 5
  portainer_start: 10
  glusterfs_setup: 30

# GlusterFS distributed storage configuration
glusterfs:
  volume_name: "swarm-storage"
  brick_path: "/gluster/brick"
  mount_point: "/mnt/gluster"
  replica_count: 2  # Replicate across 2 worker nodes

